name: .NET Core Desktop

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: windows-latest

    env:
      Solution_Name: RAYTRACER_UNILIGHT.sln
      Project_Name: RAYTRACER_UNILIGHT.csproj

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Install the .NET SDK
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      # Add MSBuild to PATH
      - name: Setup MSBuild.exe
        uses: microsoft/setup-msbuild@v2

      # Restore NuGet packages
      - name: Restore
        run: msbuild $env:Solution_Name /t:Restore /p:Configuration=${{ matrix.configuration }}

      # Build the project
      - name: Build
        run: msbuild $env:Solution_Name /p:Configuration=${{ matrix.configuration }}

      # Run tests (if you add a test project later)
      - name: Run tests
        run: dotnet test $env:Solution_Name --configuration ${{ matrix.configuration }}
        continue-on-error: true

      # Publish the project (generates an exe in artifact folder)
      - name: Publish
        run: dotnet publish $env:Project_Name -c ${{ matrix.configuration }} -o publish

      # Upload build output as artifact
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: RAYTRACER_UNILIGHT_${{ matrix.configuration }}
          path: publish/**
